### PR TITLE
Improve macOS title bar control icons

### PR DESCRIPTION
**Pull request by sergeybekrin**
This PR brings better title bar icons for macOS theme what looks exactly like native ones.

Before:
before

After:
after

### CODE REVIEW

**Comment by gabrielbull** [comment]
Hey @sergeybekrin that looks fantastic! Do you have access to a retina screen? I know they are different on a retina screen and I started making two sets of icons for new components, one for 1x screens and another for 2x and more. Here's an example of a component containing two sets of icons: https://github.com/gabrielbull/react-desktop/tree/master/src/searchField/macOs

**Comment by sergeybekrin** [comment]
@gabrielbull Sadly I don't. I know only few cases when two different icons should be used for regular and retina icons (like [playlist icon in iTunes](http://littlebigdetails.com/post/148983492672/itunes-shows-a-numbered-list-icon-for-retina)). Aligned to pixel grid vector icons looks great when zoomed, so no extra 2x icon is required.

_Zoomed version of new icons:_
Zoomed version of new icons

**Comment by gabrielbull** [comment]
They're definitely different. Most of the icons I've seen are actually a set of two different icons, one for standard displays and one for retina displays. Take a look:

capture d ecran 2016-08-25 a 23 18 59

Since I have a retina screen, I've made the retina versions myself and merged yours as the standard ones. 

Thanks a lot for your time and effort, it is much appreciated. 🍾🎊🌟

**Comment by sergeybekrin** [comment]
Did't know that! Thanks.

**Pull request merged**
