### PR TITLE
initialize test for src/Color.js

### PR DESCRIPTION
**Pull request by chentsulin**
It seems a part of function does not completed implement yet.
Are there any reasons why not just using [color](https://www.npmjs.com/package/color) npm package for doing those things?

### CODE REVIEW

**Comment by gabrielbull** [comment]
The reason was to keep dependencies and thus the footprint of the library, I was hesitant to add Radium for styling but after struggling with all the needed styling I decided to include it.

**Comment by chentsulin** [comment]
Fair enough. BTW, I thought convertColor's implement is a little weird, in general, [blue](http://www.color-hex.com/color/0000ff) should be `#0000ff`. And I also found [this](https://github.com/stylus/stylus/blob/dev/lib/colors.js), not sure whether this will be useful in this repo or not.

**Comment by gabrielbull** [comment]
Haha yeah, the blue conversion was the Windows "blue". But I figured it would be confusing as well. We should defiantly use that conversion chart, as long as the commas are at the end of the line ;-)

**Comment by chentsulin** [comment]
https://github.com/less/less.js/blob/master/lib/less/data/colors.js

This one convert color to hex, not rgba

**Comment by gabrielbull** [comment]
:+1:

**Pull request merged**
