### PR TITLE
use arrow function instead of .bind(this)

### PR DESCRIPTION
**Pull request by chentsulin**
Not sure whether you will want this or not, also it's maybe worth a try `es7.classProperties`.

### CODE REVIEW

**Comment by gabrielbull** [comment]
Yeah, they're easier to read so :+1:

**Comment by gabrielbull** [comment]
What about `es7.classProperties`?

**Comment by chentsulin** [comment]
This one: https://github.com/babel/babel/issues/619, though still a stage 1 proposal, but autobinding is too attractive. https://github.com/babel/babel/issues/619#issuecomment-71856684

**Comment by gabrielbull** [comment]
Oh yeah good for event handling I suppose, yeah lets use it!

**Comment by chentsulin** [comment]
It will be awesome :+1:

**Pull request merged**
